name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - name: Run script file
        run: ${GITHUB_WORKSPACE}/test.sh
        shell: bash
