name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get update; sudo apt-get install zsh shellcheck make git
      - name: Checks
        run: make checks
